"""
Creates structured markdown summary documents from anonymized case data.
Documents are stored locally under DOCUMENTS_DIR.
"""
import json
from datetime import datetime
from pathlib import Path
from config import settings


_TEMPLATE = """\
# Case Summary — KanoonSaathi

> **Confidential Training Document | PII Anonymized**

---

## Case Details

| Field | Value |
|-------|-------|
| **Internal ID** | {case_id} |
| **Judgment Date** | {date} |
| **Court** | Supreme Court of India |
| **Subject Area** | {subject} |
| **Acts / Statutes Cited** | {acts} |
| **Verdict** | {verdict} |

---

## Parties

| Role | Name |
|------|------|
| **Petitioner** | {petitioner} |
| **Respondent** | {respondent} |
| **Bench** | {judges} |

---

## Generated Summary

{summary}

---

## Anonymization Notice

This document has been processed by KanoonSaathi's privacy pipeline.
All personally identifiable information (names, phone numbers, Aadhaar,
PAN, email addresses) has been replaced with neutral placeholders.

| Placeholder | Type |
|-------------|------|
| John Doe / Jane Doe / Person A–H | Individual names |
| [ORGANIZATION] | Company / institution names |
| [LOCATION] | Cities, states, districts |
| [AADHAAR] | Aadhaar numbers |
| [PAN] | PAN card numbers |
| [PHONE] | Phone numbers |
| [EMAIL] | Email addresses |

---

*Generated by KanoonSaathi Pipeline · {timestamp}*
"""


def create_document(
    case_id: int,
    case_data: dict,
    summary: str,
) -> Path:
    """
    Write a markdown summary document and return its path.
    case_data keys: date, petitioner, respondent, judges, subject, acts, verdict
    """
    doc_dir = settings.documents_path()
    doc_path = doc_dir / f"case_{case_id:06d}_summary.md"

    content = _TEMPLATE.format(
        case_id=f"KS-{case_id:06d}",
        date=case_data.get("date") or "—",
        subject=case_data.get("subject") or "—",
        acts=case_data.get("acts") or "—",
        verdict=case_data.get("verdict") or "—",
        petitioner=case_data.get("petitioner") or "John Doe",
        respondent=case_data.get("respondent") or "Jane Doe",
        judges=case_data.get("judges") or "—",
        summary=summary,
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )

    doc_path.write_text(content, encoding="utf-8")

    # Also write a companion metadata JSON
    meta_path = doc_dir / f"case_{case_id:06d}_meta.json"
    meta = {
        "case_id": case_id,
        "ks_id": f"KS-{case_id:06d}",
        "date": case_data.get("date"),
        "subject": case_data.get("subject"),
        "acts": case_data.get("acts"),
        "verdict": case_data.get("verdict"),
        "document_path": str(doc_path),
        "generated_at": datetime.utcnow().isoformat(),
    }
    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")

    return doc_path
